FROM {{ baseImage }} AS base
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev
{%- for step in pmSetupSteps %}
{{ step }}
{%- endfor %}
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
RUN addgroup -S strapi && adduser -S strapi -G strapi
WORKDIR /opt/app

FROM base AS deps
{%- for file in pmCopyFiles %}
COPY {{ file }} ./
{%- endfor %}
RUN {{ pmInstallStep }}

FROM deps AS build
COPY . .
RUN {{ pmBuildStep }}

FROM {{ runtimeImage }} AS runtime
RUN apk update && apk add --no-cache vips
{%- for step in pmSetupSteps %}
{{ step }}
{%- endfor %}
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
RUN addgroup -S strapi && adduser -S strapi -G strapi
WORKDIR /opt/app
COPY --chown=strapi:strapi --from=build /opt/app .
USER strapi
EXPOSE {{ strapiPort }}
HEALTHCHECK --interval={{ healthInterval }} --timeout={{ healthTimeout }} --start-period={{ healthStartPeriod }} --retries={{ healthRetries }} \
  CMD wget --no-verbose --tries=1 --spider http://localhost:{{ strapiPort }}/_health || exit 1
CMD {{ pmDevStep }}
