import { readFileSync, existsSync } from "fs";
import { join } from "path";

export function debugEnvMerge(
  existingEnvPath: string,
  dockerSections: EnvSection[]
): void {
  console.log("🔍 Debug: Analyzing .env file merge...");

  if (existsSync(existingEnvPath)) {
    const content = readFileSync(existingEnvPath, "utf8");
    const hasDockerSection = content.includes(
      "🐳 Docker Configuration (Generated by Strapi Dockerize)"
    );

    console.log(`📁 Existing .env file: ${existingEnvPath}`);
    console.log(`🐳 Has Docker section: ${hasDockerSection}`);
    console.log(`📏 File size: ${content.length} characters`);
    console.log(`📋 Lines: ${content.split("\n").length}`);

    if (hasDockerSection) {
      console.log("✅ Will replace existing Docker configuration section");
    } else {
      console.log("➕ Will append new Docker configuration section");
    }
  } else {
    console.log("📝 No existing .env file, will create new one");
  }

  console.log(`🔧 Docker sections to add: ${dockerSections.length}`);
  dockerSections.forEach((section, i) => {
    console.log(
      `  ${i + 1}. ${section.title} (${section.variables.length} variables)`
    );
  });
}

export interface EnvVariable {
  key: string;
  value: string;
  comment?: string;
}

export interface EnvSection {
  title: string;
  variables: EnvVariable[];
}

export function parseEnvFile(filePath: string): Map<string, string> {
  const envMap = new Map<string, string>();

  if (!existsSync(filePath)) {
    return envMap;
  }

  const content = readFileSync(filePath, "utf8");
  const lines = content.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip comments and empty lines
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }

    // Parse KEY=VALUE
    const equalIndex = trimmed.indexOf("=");
    if (equalIndex > 0) {
      const key = trimmed.substring(0, equalIndex).trim();
      const value = trimmed.substring(equalIndex + 1).trim();
      envMap.set(key, value);
    }
  }

  return envMap;
}

export function mergeEnvVariables(
  existingEnvPath: string,
  dockerSections: EnvSection[]
): string {
  const dockerKeys = new Set<string>();

  // Collect all Docker keys
  for (const section of dockerSections) {
    for (const variable of section.variables) {
      dockerKeys.add(variable.key);
    }
  }

  let result = "";

  // Add existing file content (preserve comments and structure)
  if (existsSync(existingEnvPath)) {
    const existingContent = readFileSync(existingEnvPath, "utf8");
    const lines = existingContent.split("\n");

    let inDockerSection = false;
    let foundDockerSection = false;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const trimmed = line.trim();

      // Check if we're entering our specific Docker configuration section
      if (
        trimmed.includes(
          "🐳 Docker Configuration (Generated by Strapi Dockerize)"
        )
      ) {
        inDockerSection = true;
        foundDockerSection = true;

        // Also skip the preceding separator line if it exists
        if (i > 0 && lines[i - 1].trim().startsWith("# ====")) {
          // Remove the last line we added (the separator)
          result = result.replace(/[^\n]*\n$/, "");
        }
        continue;
      }

      // Check if we're leaving Docker section (next section or end of file)
      if (inDockerSection) {
        // We're still in Docker section, skip this line
        // We exit the section when we hit a new major section or end of file
        // Look for next major comment section that's not our Docker stuff
        if (
          trimmed.startsWith("# ===") &&
          !trimmed.includes("Docker Configuration")
        ) {
          // Found the start of a new major section, exit Docker section
          inDockerSection = false;
          result += line + "\n";
        } else if (i === lines.length - 1) {
          // End of file while in Docker section
          inDockerSection = false;
        }
        // Skip all other lines while in Docker section
        continue;
      }

      // Not in Docker section, preserve the line
      // But skip Docker-related variables that might be scattered throughout
      if (!dockerKeys.has(trimmed.split("=")[0]?.trim())) {
        result += line + "\n";
      }
    }

    // Clean up extra newlines, but preserve some structure
    result = result.replace(/\n{4,}/g, "\n\n\n");
    result = result.replace(/\n{3}$/, "\n\n");
  }

  // Add Docker configuration sections
  if (result && !result.endsWith("\n")) {
    result += "\n";
  }
  if (result && !result.endsWith("\n\n")) {
    result += "\n";
  }

  result += "# ==============================================\n";
  result += "# 🐳 Docker Configuration (Generated by Strapi Dockerize)\n";
  result += "# ==============================================\n\n";

  for (const section of dockerSections) {
    result += `# ${section.title}\n`;

    for (const variable of section.variables) {
      if (variable.comment) {
        result += `# ${variable.comment}\n`;
      }
      result += `${variable.key}=${variable.value}\n`;
    }

    result += "\n";
  }

  return result;
}

export function createDockerEnvSections(templateVars: any): EnvSection[] {
  const databaseVariables = [
    { key: "DATABASE_CLIENT", value: templateVars.database.client },
  ];

  // SQLite uses different environment variables
  if (templateVars.database.client === "sqlite") {
    databaseVariables.push({
      key: "DATABASE_FILENAME",
      value: `./data/${templateVars.database.name}`,
    });
  } else {
    // PostgreSQL, MySQL, MariaDB use connection details
    databaseVariables.push(
      { key: "DATABASE_HOST", value: templateVars.database.serviceName },
      { key: "DATABASE_PORT", value: templateVars.database.port.toString() },
      { key: "DATABASE_NAME", value: templateVars.database.name },
      { key: "DATABASE_USERNAME", value: templateVars.database.user },
      { key: "DATABASE_PASSWORD", value: templateVars.database.password }
    );
  }

  return [
    {
      title: "Database",
      variables: databaseVariables,
    },
    {
      title: "Secrets (Generated automatically - keep these secure!)",
      variables: [
        { key: "JWT_SECRET", value: templateVars.secrets.jwt },
        { key: "ADMIN_JWT_SECRET", value: templateVars.secrets.adminJwt },
        { key: "APP_KEYS", value: templateVars.secrets.appKeys },
      ],
    },
    {
      title: "Environment",
      variables: [
        { key: "NODE_ENV", value: templateVars.environment },
        {
          key: "# STRAPI_URL",
          value: "https://api.example.com",
          comment: "Optional: Strapi Server URL (uncomment for production)",
        },
      ],
    },
  ];
}
