import { readFileSync, existsSync } from "fs";
import { join } from "path";

export interface EnvVariable {
  key: string;
  value: string;
  comment?: string;
}

export interface EnvSection {
  title: string;
  variables: EnvVariable[];
}

// Known Strapi environment variable categories
const STRAPI_DATABASE_KEYS = new Set([
  "DATABASE_CLIENT",
  "DATABASE_HOST",
  "DATABASE_PORT",
  "DATABASE_NAME",
  "DATABASE_USERNAME",
  "DATABASE_PASSWORD",
  "DATABASE_FILENAME", // SQLite
  "DATABASE_URL", // Alternative connection string format
]);

const STRAPI_SECRET_KEYS = new Set([
  "JWT_SECRET",
  "ADMIN_JWT_SECRET",
  "APP_KEYS",
  "API_TOKEN_SALT",
  "TRANSFER_TOKEN_SALT",
]);

const STRAPI_CORE_KEYS = new Set([
  "NODE_ENV",
  "STRAPI_URL",
  "HOST",
  "PORT",
  "STRAPI_ADMIN_BACKEND_URL",
  "STRAPI_ADMIN_CLIENT_URL",
  "STRAPI_ADMIN_CLIENT_PREVIEW_SECRET",
]);

export function debugEnvMerge(
  existingEnvPath: string,
  dockerSections: EnvSection[]
): void {
  // Only show debug info in development mode
  if (process.env.NODE_ENV !== "development") {
    return;
  }

  console.log("🔍 Debug: Analyzing smart .env merge...");

  if (existsSync(existingEnvPath)) {
    const existingVars = parseEnvFile(existingEnvPath);
    const dbVars = Array.from(existingVars.keys()).filter((key) =>
      STRAPI_DATABASE_KEYS.has(key)
    );

    console.log(`📁 Existing .env: ${existingEnvPath}`);
    console.log(`🗄️  Existing database vars: ${dbVars.join(", ")}`);
    console.log(
      `🔐 Has secrets: ${Array.from(existingVars.keys()).some((key) =>
        STRAPI_SECRET_KEYS.has(key)
      )}`
    );
  } else {
    console.log("📝 No existing .env file, creating new one");
  }

  console.log(`🔧 Docker sections to merge: ${dockerSections.length}`);
}

export function parseEnvFile(filePath: string): Map<string, string> {
  const envMap = new Map<string, string>();

  if (!existsSync(filePath)) {
    return envMap;
  }

  const content = readFileSync(filePath, "utf8");
  const lines = content.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip comments and empty lines
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }

    // Parse KEY=VALUE
    const equalIndex = trimmed.indexOf("=");
    if (equalIndex > 0) {
      const key = trimmed.substring(0, equalIndex).trim();
      const value = trimmed.substring(equalIndex + 1).trim();
      envMap.set(key, value);
    }
  }

  return envMap;
}

export function smartMergeEnvFile(
  existingEnvPath: string,
  dockerSections: EnvSection[]
): string {
  let result = "";

  if (existsSync(existingEnvPath)) {
    const existingContent = readFileSync(existingEnvPath, "utf8");
    const lines = existingContent.split("\n");

    let inDockerSection = false;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const trimmed = line.trim();

      // Skip our generated Docker section completely
      if (
        trimmed.includes("🐳 Docker Configuration") ||
        trimmed.includes("Generated by Strapi Dockerize") ||
        trimmed.includes("====")
      ) {
        inDockerSection = true;
        continue;
      }

      // Exit Docker section when we hit content again
      if (inDockerSection) {
        // Look for the end of Docker section (empty lines followed by content)
        if (trimmed && !trimmed.startsWith("#")) {
          if (trimmed.includes("=")) {
            const key = trimmed.split("=")[0].trim();
            // If it's not a database variable, we've exited the Docker section
            if (!STRAPI_DATABASE_KEYS.has(key)) {
              inDockerSection = false;
            }
          } else {
            inDockerSection = false;
          }
        }
      }

      // Skip lines in Docker section
      if (inDockerSection) {
        continue;
      }

      // Parse and filter variables
      if (trimmed && !trimmed.startsWith("#") && trimmed.includes("=")) {
        const key = trimmed.split("=")[0].trim();

        // Skip database variables that will be replaced by Docker config
        if (STRAPI_DATABASE_KEYS.has(key)) {
          console.log(`🔄 Replacing existing database config: ${key}`);
          continue;
        }
      }

      // Preserve everything else (maintaining original structure)
      result += line + "\n";
    }
  }

  // Clean up trailing whitespace but preserve some structure
  result = result.replace(/\n{3,}$/, "\n\n");

  // Add Docker configuration at the end
  result += "# ==============================================\n";
  result += "# 🐳 Docker Configuration (Generated by Strapi Dockerize)\n";
  result += "# ==============================================\n\n";

  // Only add database config (secrets are preserved from original)
  const databaseSection = dockerSections.find((s) =>
    s.title.includes("Database")
  );
  if (databaseSection) {
    result += `# ${databaseSection.title}\n`;
    for (const variable of databaseSection.variables) {
      result += `${variable.key}=${variable.value}\n`;
    }
  }

  return result;
}

// Legacy function name for backward compatibility
export function mergeEnvVariables(
  existingEnvPath: string,
  dockerSections: EnvSection[]
): string {
  return smartMergeEnvFile(existingEnvPath, dockerSections);
}

export function createDockerEnvSections(
  templateVars: any,
  existingEnvPath?: string
): EnvSection[] {
  const databaseVariables = [
    {
      key: "DATABASE_CLIENT",
      value: templateVars.database.client,
      comment: `Database type: ${templateVars.database.client}`,
    },
  ];

  // SQLite uses different environment variables
  if (templateVars.database.client === "sqlite") {
    // For SQLite, preserve existing filename if it exists, otherwise use Strapi default
    let sqliteFilename = ".tmp/data.db"; // Strapi default SQLite path

    if (existingEnvPath && existsSync(existingEnvPath)) {
      const existingVars = parseEnvFile(existingEnvPath);
      const existingFilename = existingVars.get("DATABASE_FILENAME");
      if (existingFilename) {
        sqliteFilename = existingFilename;
      }
    }

    databaseVariables.push({
      key: "DATABASE_FILENAME",
      value: sqliteFilename,
      comment: "SQLite database file path",
    });
  } else {
    // PostgreSQL, MySQL, MariaDB use connection details
    databaseVariables.push(
      {
        key: "DATABASE_HOST",
        value: templateVars.database.serviceName,
        comment: "Database container hostname",
      },
      {
        key: "DATABASE_PORT",
        value: templateVars.database.port.toString(),
        comment: "Database port",
      },
      {
        key: "DATABASE_NAME",
        value: templateVars.database.name,
        comment: "Database name",
      },
      {
        key: "DATABASE_USERNAME",
        value: templateVars.database.user,
        comment: "Database username",
      },
      {
        key: "DATABASE_PASSWORD",
        value: templateVars.database.password,
        comment: "Database password (keep secure!)",
      }
    );
  }

  // Only return database configuration - secrets are preserved from original file
  return [
    {
      title: "Database Configuration",
      variables: databaseVariables,
    },
  ];
}

export function detectExistingEnvConfig(envPath: string): {
  hasDatabase: boolean;
  hasSecrets: boolean;
  databaseType?: string;
  customVars: string[];
} {
  const result = {
    hasDatabase: false,
    hasSecrets: false,
    databaseType: undefined as string | undefined,
    customVars: [] as string[],
  };

  if (!existsSync(envPath)) {
    return result;
  }

  const envVars = parseEnvFile(envPath);

  // Check for database config
  result.hasDatabase = Array.from(envVars.keys()).some((key) =>
    STRAPI_DATABASE_KEYS.has(key)
  );

  // Detect database type
  result.databaseType = envVars.get("DATABASE_CLIENT");

  // Check for secrets
  result.hasSecrets = Array.from(envVars.keys()).some((key) =>
    STRAPI_SECRET_KEYS.has(key)
  );

  // Find custom variables (not Strapi core)
  for (const [key] of envVars) {
    if (
      !STRAPI_DATABASE_KEYS.has(key) &&
      !STRAPI_SECRET_KEYS.has(key) &&
      !STRAPI_CORE_KEYS.has(key)
    ) {
      result.customVars.push(key);
    }
  }

  return result;
}
